development:
  adapter: postgresql
  encoding: unicode
  database: barklist_development
  pool: 5
  username: donald
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: barklist_test
  pool: 5
  username: donald
  password:
